#!/usr/bin/env bash
# This script displays the part of filenames after the first dash using a for loop
for file in *
do
    if [[ $file != .* ]]  # Skip hidden files
    then
        echo "${file#*-}"
    fi
done
