#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and displays different messages for 4 and 8.

COUNT=1
while [ "$COUNT" -le 10 ]; do
    if [ "$COUNT" -eq 4 ]; then
        echo "bad luck"
    elif [ "$COUNT" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    COUNT=$((COUNT + 1))
done
